// <auto-generated />
using System;
using CQRSTesting.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CQRSTesting.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CQRSTesting.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("331f5ce3-5357-4bd5-acc9-c44ce04f4040"),
                            DateCreated = new DateTime(2023, 6, 27, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5552),
                            DatePublished = new DateTime(2023, 6, 28, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5562),
                            Description = "Test Product",
                            Name = "Product 1",
                            UnitPrice = 100m
                        },
                        new
                        {
                            ProductId = new Guid("e27f324b-c16b-428e-a2b9-7911ee652ca4"),
                            DateCreated = new DateTime(2023, 6, 27, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5599),
                            DatePublished = new DateTime(2023, 6, 28, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5600),
                            Description = "Test Product",
                            Name = "Product 2",
                            UnitPrice = 120m
                        },
                        new
                        {
                            ProductId = new Guid("398d3c2d-e5ee-4fb9-8978-a351ba15c432"),
                            DateCreated = new DateTime(2023, 6, 27, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5613),
                            DatePublished = new DateTime(2023, 6, 28, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5614),
                            Description = "Test Product",
                            Name = "Product 3",
                            UnitPrice = 500m
                        },
                        new
                        {
                            ProductId = new Guid("935c8090-d996-4903-9bee-69d478b621e0"),
                            DateCreated = new DateTime(2023, 6, 27, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5626),
                            DatePublished = new DateTime(2023, 6, 28, 11, 29, 51, 436, DateTimeKind.Local).AddTicks(5626),
                            Description = "Test Product",
                            Name = "Product 4",
                            UnitPrice = 80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
